apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dsf-301-numa1p0-pf3
  annotations:
    k8s.v1.cni.cncf.io/resourceName: aws-cse-lc-bundle/mlnx_sriov_netdevice 
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "vlan": 301,
  "logLevel": "debug",
  "ipam": {
        "type": "static",
        "addresses": [{"address": "169.30.1.100/24"}]
      }
}'
